[package]
name = "first_lib_yulian"
license = "MIT"
description = "My first library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
